[package]
name = "wise-platform"
description = "Wise Platform API client using progenitor"
authors = ["Liam Kinne <liam@kinne.io>"]
version = "0.1.0"
edition = "2024"
license = "MIT"
readme = "README.md"
repository = "https://github.com/liamkinne/wise-rs"

[build-dependencies]
serde_json = "1.0"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3"
progenitor = "0.14"
regress = "0.11"
reqwest = { version = "0.13", features = ["json", "query", "stream", "form"] }
serde_json = "1.0"
serde = "1.0"
uuid = { version = "1.24", features = ["serde", "v4"] }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
